apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appcontroller
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:sahil-R/test-yaml.git
    path: applicationset
  destination:
    server: https://kubernetes.default.svc
    namespace: default
