apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appcontroller
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:sahil-R/test-yaml.git
    targetRevision: HEAD
    path: application-set.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
