apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appcontroller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sahil-R/test-yaml.git
    path: applicationset
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
