apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydeployment2
  namespace: default
spec:
  project: myproject
  source:
    repoURL: https://github.com/sahil-R/test-yaml.git
    path: helm-project
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}