apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mysql.servicename}}
spec:
  selector:
    app: {{.Values.mysql.selector.appname}}
  ports:
    - protocol: {{.Values.mysql.ports.protocol}}
      port: {{.Values.mysql.ports.port}}
      targetPort: {{.Values.mysql.ports.targetport}}
