apiVersion: v1
kind: Service
metadata:
  name: {{.Values.redis.servicename}}
spec:
  selector:
    app: {{.Values.redis.selector.appname}}
  ports:
    - protocol: {{.Values.redis.ports.protocol}}
      port: {{.Values.redis.ports.port}}
      targetPort:  {{.Values.redis.ports.targetport}}
