apiVersion: v1
kind: Service
metadata:
  name: {{.Values.wordpress.servicename}}
spec:
  type: NodePort
  selector:
    app: {{.Values.wordpress.selector.appname}}
  ports:
    - protocol: {{.Values.wordpress.ports.protocol}}
      port: {{.Values.wordpress.ports.port}}
      targetPort: {{.Values.wordpress.ports.targetport}}
