apiVersion: apps/v1
kind: Deployment
metadata:
  
  name: {{.Values.wordpress.appname}}
  labels:
    app: {{.Values.wordpress.appname}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.wordpress.appname}}
  template:
    metadata:
      labels:
        app: {{.Values.wordpress.appname}}
    spec:
      containers:
      - name: {{.Values.wordpress.appname}}
        image: {{.Values.wordpress.image}}
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_USER
          value: {{.Values.wordpress.env.dbuser}}
        - name: WORDPRESS_DB_PASSWORD
          value: {{.Values.wordpress.env.dbpass}}
        - name: WORDPRESS_DB_NAME
          value: {{.Values.wordpress.appname}}
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
                define('WP_REDIS_HOST', 'redis-service');
                define( 'WP_REDIS_PORT', '6379' );
                define( 'WP_CACHE', true );
        ports:
        - containerPort: {{.Values.wordpress.ports.port}}
