apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapplicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: mydeployment1
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-test'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/sahil-R/test-yaml.git
        path: helm-project
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated: {}