apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapplicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: staging
        url: https://kubernetes.default.svc
      - cluster: production
        url: gke_sahilr_us-central1-c_production
  template:
    metadata:
      name: '{{cluster}}-test'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/sahil-R/test-yaml.git
        path: helm-project
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated: {}